version: "3.9"
   
services:
  frontend:
    image: stellara-frontend:${STELLARA_DOCKER_TAG}
    ports:
      - "8080:80"
    depends_on:
      - gqrx
  gqrx:
    image: gqrx-remote-rest:${GQRX_DOCKER_TAG}
    environment:
      - GQRX_HOST=${GQRX_HOST}
      - GQRX_PORT=${GQRX_PORT} 
    ports:
      - "3030:3030"
  http:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "2001:80"
    depends_on:
      - gqrx
      - frontend